# docker-compose.yml

subsonic:
  build: .
  ports:
  - 127.0.0.1:40000:8080
  volumes:
  - /local/var/playlists:/var/playlists
  - /local/var/music:/var/music:ro
  - /local/var/subsonic:/var/subsonic
